### ISSUE TITLE
Roadmap: Flow Type Repositories + Flow Type Editor

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-plugins#14]
```mermaid
gitGraph
   commit
   branch plugin_git
   checkout plugin_git
   commit id: "git clone"
   commit id: "git fetch"
   commit id: "git checkout"
   branch plugin_flow_repository
   checkout plugin_flow_repository
   commit id: "index flow repositories"
   commit id: "register new flow types"
   branch plugin_flow_editor
   checkout plugin_flow_editor
   commit id: "edit flow type"
   commit id: "create flow instance from flow type"
   commit id: "save flow type"
   checkout plugin_flow_repository
   merge plugin_flow_editor
   commit id: "commit flow type"
   checkout plugin_git
   commit id: "git commit"
   commit id: "git push"
   checkout plugin_flow_repository
   merge plugin_git
   commit id: "push flow type"
   checkout plugin_git
   merge plugin_flow_repository
   checkout main
   merge plugin_git
```

## Tasks

- [x] Git: git clone
- [x] Git: git fetch
- [ ] Git: git checkout
- [ ] Flow Type Repository: index flow type repository
- [ ] Flow Type Repository: register flow type
- [ ] Flow Type Editor: edit flow type
- [ ] Flow Type Editor: create flow instance from flow type
- [ ] Flow Type Editor: update / save / export flow type
- [ ] Flow Type Repository: commit flow type
- [ ] Git: git commit
- [ ] Git: git push
- [ ] Flow Type Repository: push flow type
