### ISSUE TITLE
Plugin Web Resource Repository

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-plugins#16]
## Goal

Generic way to serve frontend applications provided by a git repository.

## Tasks

- [ ] Component `web_resource::repository`
  - [ ] Read `package.json`
  - [ ] Property `build` → Run a build using yarn
- [ ] `WebResourceProvider`
  - [ ] Delegate requests `/web-resource/{.*:web_resource_name}/**` to `dist/{web_resource_name}/**`

## Depends on

* plugin git
