### ISSUE TITLE
Plugin HTTP: Handle incoming POST and GET requests

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-plugins#20]
## Goal

Make it possible to set reactive properties from external applications.

## Tasks

- [ ] Add a web resource provider for endpoint `http`
- [ ] Handle GET Requests and return the value of the property
  - [ ] GET `/http/entities/{uuid}/{property}` ⇒ JSON Response
  - [ ] GET `/http/entities/{uuid}/{property}/set/{value}`
  - [ ] GET `/http/{labelPath}/{property}` ⇒ JSON Response
  - [ ] GET `/http/{labelPath}/{property}/set/{value}`
  - [ ] Error Return Code 403 if the property is immutable
  - [ ] Error Return Code 404 if the entity or the property does not exist
- [ ] Handle PUT Requests and change the value of the property
  - [ ] PUT `/http/entities/{uuid}/{property}` ⇐ JSON Payload
  - [ ] PUT `/http/{labelPath}/{property}` ⇐ JSON Response
  - [ ] Error Return Code 400 if the data type does not match with the property data type
  - [ ] Error Return Code 403 if the property is immutable
  - [ ] Error Return Code 404 if the entity or the property does not exist

## Use Cases

- [ ] External UIs can read data via HTTP
- [ ] External programs that can send HTTP requests
