### ISSUE TITLE
Time Graph

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-plugins#21]
### Goal

The time graph (or [time tree](https://www.markhneedham.com/blog/2014/04/19/neo4j-cypher-creating-a-time-tree-down-to-the-day/) ) is a technique to represent temporal data in a new way.

* Date Representation
* Date Graph Navigation

### Use Cases

* Date Parsing
* Date Calculation
* Scheduling → Feed the scheduler → Automate time based tasks
* Timers → Feed the scheduler → Automate time based tasks
* Asset Management → Organize assets by temporal relations
* Game Statistics → Link statistical data with a given date time

### Tasks

- [x] Entity Types
  - [x] Year
  - [x] Month
  - [x] Day
  - [x] Hour
  - [x] Minute
- [x] Relation Types
  - [x] Next Year
  - [x] Month of Year
  - [x] First Month
  - [x] Next Month
  - [x] Day of Month
  - [x] First Day
  - [x] Last Day
  - [x] Next Day
- [x] Create Time Graph Forrest

**Comment by aschaeffer** [comment]
A basic time graph is implemented.

Further work:

* It would be nice to define colors for the graph representation in an extension `node_color`, e.g. years in blue, months in green, ...
* Automatically create time graph nodes if needed
* Enhance the Dynamic Graph with specialized functionalities regarding the time graph
  * connect/disconnect any node with a time graph node
  * query for
* Ranges (e.g. years `2022 - 2023` or days `2023-01-04 - 2024-06-24`)
