### ISSUE TITLE
Date Calculation

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-plugins#23]
### Goal

Calculate with dates (#8) and durations (#22).

### Entity Types

| Name           | Components | Properties | DataType | SocketType | Description                                           |
|----------------|------------|------------|----------|------------|-------------------------------------------------------|
||
| datetime_plus  |            | datetime   | string   | input      | Adds the given duration from the given date time      |
|                |            | duration   | string   | input      | The duration to add (ISO8601 duration format)         |
|                |            | result     | string   | output     | The calculated date time as ISO8601                   |
||
| datetime_minus |            | datetime   | string   | input      | Subtracts the given duration from the given date time |
|                |            | duration   | string   | input      | The duration to subtract (ISO8601 duration format)    |
|                |            | result     | string   | output     | The calculated date time as ISO8601                   |
||
| datetime_diff  |            | datetime   | string   | input      | Calculates the difference of two datetimes            |
|                |            | datetime   | string   | input      |                                                       |
|                |            | result     | string   | output     | The calculated difference as ISO8601 duration format  |

### Tasks

- [ ] Entity Type + Behaviour `datetime_plus`
- [ ] Entity Type + Behaviour `datetime_minus`
- [ ] Entity Type + Behaviour `datetime_diff`
