### ISSUE TITLE
Date Comparison

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-plugins#24]
### Goal

Compares two dates with each other.

### Entity Types

| Name           | Components | Properties | DataType | SocketType | Description                                           |
|----------------|------------|------------|----------|------------|-------------------------------------------------------|
| equals         |            | lhs        | string   | input      | A datetime|
|                |            | rhs        | string   | input      | Another datetime|
|                |            | result     | bool     | output     | True, if both datetimes are equal        |
||
| before         |            | lhs        | string   | input      | A datetime|
|                |            | rhs        | string   | input      | Another datetime|
|                |            | result     | bool     | output     | True, if lhs is before rhs |
||
| after          |            | lhs        | string   | input      | A datetime|
|                |            | rhs        | string   | input      | Another datetime|
|                |            | result     | bool     | output     | True, if lhs is after rhs |

### Tasks

- [ ] Entity Type + Behaviour `equals`
- [ ] Entity Type + Behaviour `before`
- [ ] Entity Type + Behaviour `after`
