### ISSUE TITLE
Ranges

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-plugins#25]
### Goal

Represent numeric ranges.

### Use cases

* Geometric operations
* Iterators

### Tasks

- [ ] Component Range
  - [ ] Property min (number)
  - [ ] Property max (number)
- [ ] Model
  - [ ] `to_range() -> Range`
  - [ ] `from_range(r: Range) -> Component`
- [ ] Entity Types
  - [ ] `range__to_array`
    - [ ] Component `range__range`
      - [ ] Input-Property min (number)
      - [ ] Input-Property max (number)
    - [ ] Component `result__array_result`
      - [ ] Output-Property `result`
    - [ ] Behaviour `range__to_array`
      - [ ] `(min..max).collect()`
  - [ ] `range__contains`
    - [ ] Component `range__range`
      - [ ] Input-Property min (number)
      - [ ] Input-Property max (number)
    - [ ] Component `result__bool_result`
      - [ ] Output-Property `result`
    - [ ] Behaviour `range__contains`
      - [ ] https://doc.rust-lang.org/std/ops/struct.Range.html#method.contains

### Reference

* https://doc.rust-lang.org/std/ops/struct.Range.html

### Follow Up

- [ ] Iterators
